#ifndef APP_AUDIO_CFG_H
#define APP_AUDIO_CFG_H
#define APP_ADC_MDF_CLK_SRC_MSIK   0
#define APP_ADC_MDF_CLK_SRC_PLL    1
#define APP_ADC_MDF_CLK_SRC_SEL    APP_ADC_MDF_CLK_SRC_MSIK
#define APP_ADC_MDF_KERNEL_2048K   3
#define APP_ADC_MDF_KERNEL_SEL     APP_ADC_MDF_KERNEL_2048K
#endif
